#!/bin/bash

if [ -f "/bin/rudraksh" ] ; then
   rm  /bin/rudraksh /bin/parseimages /bin/utils /bin/doclist.csv
fi

hostnamectl set-hostname Rudraksh

curl -s -o /bin/utils https://raw.githubusercontent.com/RavikumarRamesh/RudrakshLab/main/utils

source utils

#Add Swap memory
#swap_add

# Update and Upgrade the current kali system
update_upgrade

#Install docker
docker_install

#Login into the docker hub account - Replace valid credentials in this script
docker_login

#Install Docker compose + required tools
install_tool

# If docker already install then stop all containers and forcefully clean the images
all_docker_img_remove 

# Download launcher and utils
curl -s -o /bin/rudraksh https://raw.githubusercontent.com/RavikumarRamesh/RudrakshLab/main/rudraksh
curl -s -o /bin/parseimages https://raw.githubusercontent.com/RavikumarRamesh/RudrakshLab/main/parseimages

reboot
