#!/bin/bash

if [ -f "/bin/fresh" ] ; then
   rm /bin/rudraksh /bin/parseimages /bin/utils /bin/fresh /bin/doclist.csv
fi

hostnamectl set-hostname Rudraksh

rm /bin/doclist.csv

curl -s -o  /bin/utils https://raw.githubusercontent.com/RavikumarRamesh/RudrakshLab/main/utils  
curl -s -o  /bin/fresh https://raw.githubusercontent.com/RavikumarRamesh/RudrakshLab/main/fresh 
curl -s -o  /bin/doclist.csv https://raw.githubusercontent.com/RavikumarRamesh/RudrakshLab/main/doclist.csv  
curl -s -o  /bin/rudraksh https://raw.githubusercontent.com/RavikumarRamesh/RudrakshLab/main/rudraksh 
curl -s -o  /bin/parseimages https://raw.githubusercontent.com/RavikumarRamesh/RudrakshLab/main/parseimages 

chmod +x /bin/rudraksh /bin/parseimages /bin/utils /bin/fresh 

source /bin/utils

swap_add

# Update and Upgrade the current Kali system
update_upgrade

#Install docker
docker_install

#Install Docker compose + required tools
install_tool

fresh

#reboot
