#!/bin/bash
#
# Support functions for Lab

LOGFILENAME="docker.log"

log () {
export LOGFILE="$LOGFILENAME"
   if [ "$LOGFILE" ]
   then
      echo "$*" >> $LOGFILE
   else
      touch "$LOGFILENAME"
      echo "$*" >> $LOGFILE
   fi
}

function ctrl_c() {
       temp=$(tty)
       ps -ef | grep sshd | grep @${temp:5} | awk '{print "kill -9", $2}' | sh
}

swap_add () {

}

all_docker_stop () {
        docker stop $(docker ps -a -q)
}

all_docker_remove () {
         docker stop $(docker ps -a -q)
         docker rm $(docker ps -a -q)
         #Clear Cache in Linux
	      sync; echo 1 > /proc/sys/vm/drop_caches
	      sync; echo 2 > /proc/sys/vm/drop_caches
	      sync; echo 3 > /proc/sys/vm/drop_caches
}

all_docker_img_remove (){
        docker stop $(docker ps -a -q)
        docker rm $(docker ps -a -q)
        docker rmi -f $(docker images -a -q)
        #Clear Cache in Linux
	     sync; echo 1 > /proc/sys/vm/drop_caches
	     sync; echo 2 > /proc/sys/vm/drop_caches
	     sync; echo 3 > /proc/sys/vm/drop_caches
}

docker_login (){
      
}

update_upgrade (){
      apt-get -y update
      apt-get -y upgrade
}

docker_install (){
      apt install -y docker.io
      systemctl enable docker --now
}

install_tool (){
      apt-get -y install git dialog 
}

google_auth_setup (){
  
}

add_root_sshkey (){
 
}
